name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: integralsw/osa-python:auto-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run Notebook
      run: |
        pwd
        ls -ltor
        ls -ltor /init.sh
        ls -lotr /
        cat init.sh
        export HOME_OVERRRIDE=/tmp
        source /init.sh
        pip install papermill 
        papermill count-flux-conversion.ipynb count-flux-conversion-output.ipynb
