name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: integralsw/osa-python:auto-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run Notebook
      run: |
        cat /init.sh
        
        source /etc/pyenvrc
        which python
        pip install papermill 
        export HOME_OVERRRIDE=/tmp 
        export
        source /init.sh
        papermill count-flux-conversion.ipynb count-flux-conversion-output.ipynb
